### ISSUE TITLE
Rossz API kulcssal fatal error

### ISSUE THREAD

**Issue by passatgt** [voov/Billingo-API-Connector#1]
Üdv!

Ha rossz api kulccsal próbálok csatlakozni(szeretném lekezelni, ha rosszul adták meg), ezt a hibát kapom:

<br />
<b>Fatal error</b>:  Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `GET https://www.billingo.hu/api/clients` resulted in a `500 Internal Server Error` response:
{&quot;success&quot;:false,&quot;error&quot;:&quot;User not found!&quot;} 

Válasz ott van, csak internal server error miatt nem tudom feldolgozni.

**Comment by danfekete** [comment]
Ezt javítani fogjuk mielőbb, köszi az észrevételt, elvileg 403 -as hibával fog visszatérni (ettől még elvileg a Guzzle fog exceptiont dobni)

**Comment by danfekete** [comment]
A mai hotfix-ben már jól lesz benne, hogy hibás tokennél 403-as hibát dob
