### ISSUE TITLE
Számla létrehozás válaszában több helyen is üres az invoice_no

### ISSUE THREAD

**Issue by Razoralpha** [voov/Billingo-API-Connector#15]
Dokumentáció szerint:
"invoice_number": "2014-000005",
Gyakorlatban:
"invoice_number": "",

Így kénytelenek voltunk az alábbi kóddal összerakni a számla azonosítóját:
$responseProformaGeneration["attributes"]["prefix"] ."-". str_pad($responseProformaGeneration["attributes"]["items"][0]["invoice"]["sequence"], 6, "0", STR_PAD_LEFT)

**Comment by danfekete** [comment]
Proforma számla esetén nincs számlaszám, csak kizárólag végszámlák kapnak számlaszámot

**Comment by Razoralpha** [comment]
Lehetséges egy olyan feature request, hogy ebben az esetben szerepeljen proforma_no-ként, hogy ne kelljen felpaddelni a fenti módon, de mégis el tudjuk menteni az oldalon használt formátumban?
