### ISSUE TITLE
Hiba az IPv6 címekkel az eu/vat API végpontjukon

### ISSUE THREAD

**Issue by Razoralpha** [voov/Billingo-API-Connector#16]
A vat/eu végpont
`file_get_contents(http://ip2c.org/2a01:4a80:0:5000::20): failed to open stream: HTTP reques(truncated...)`
választ ad mivel a
http://ip2c.org/2a01:4a80:0:5000::20 
`0;;;WRONG INPUT`-al tér vissza.

Lehetséges ennek a javítása, esetleg csak opcionálissá tétele, hogy az adott országhoz tartozó adókulcs azonosítóját azért vissza lehessen kapni?

**Comment by danfekete** [comment]
IPv6 -ot nem támogatunk egyelőre, IPv4 formátumban kell megadni a végponton

**Comment by Razoralpha** [comment]
A felhasználóknak sajnos nem minden esetben van IPv4 címe, főleg mobilnetről,
nem jelentene gondot, ha nem lenne az api szempontjából kötelező a lekérésben.
A dokumentáció szerint viszont kötelező: 
> ip (required) the IP address of the user

Így viszont nem tudjuk lekérni annak az vevőnek az EU VAT adókulcs azonosítóját aki így érkezik.
Megakad a fizetésben.
