### ISSUE TITLE
Időzóna vs JWT Token generlás

### ISSUE THREAD

**Issue by passatgt** [voov/Billingo-API-Connector#3]
Valam időzóna gond lehet... Tegnap próbáltam akkor még működött minden, ma viszont ezt a hibát kapom:

```
[20-Apr-2016 13:04:03 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://www.billingo.hu/api/clients` resulted in a `500 Internal Server Error` response:
{"success":false,"error":"Cannot handle token prior to 2016-04-20T15:04:03+0200"}
 in ....../vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 .....vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1  ...../vendor/guzzlehttp/promises/src/Promise.php(201): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2  ...../vendor/guzzlehttp/promises/src/Promise.php(154) in  ...../vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107
```

**Comment by danfekete** [comment]
A szerveren amiről próbáltad, hogyan van beállítva az időzóna?

**Comment by passatgt** [comment]
UTC volt, mos átállítottam Europe/Budapest-re, viszont így sem akar menni:

```
[21-Apr-2016 12:33:00 Europe/Budapest] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://www.billingo.hu/api/clients` resulted in a `500 Internal Server Error` response:
{"success":false,"error":"Cannot handle token prior to 2016-04-21T12:32:59+0200"}
```

**Comment by danfekete** [comment]
Milyen `iat` és `nbf` adsz át a tokennek? Állítottál bármit rajta?

**Comment by passatgt** [comment]
Nem állítottam semmit, és itt van amit átadok, ez akkor volt, amikor a kommentet írtam.

```
Array
(
    [sub] => 3433719e92d4a35811291223b8d06fb9
    [iat] => 1461250027
    [exp] => 1461250087
    [iss] => /develop/wp-admin/admin-ajax.php
    [nbf] => 1461250027
    [jti] => 3f370d468d03eb7a25d85576a8852f7e
)
```

```
[21-Apr-2016 16:47:07 Europe/Budapest] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://www.billingo.hu/api/clients` resulted in a `500 Internal Server Error` response:
{"success":false,"error":"Cannot handle token prior to 2016-04-21T16:47:07+0200"}
```

**Comment by danfekete** [comment]
Ha lefutattsz PHP-ból egy `time` -ot, majd http://www.epochconverter.com/ -el megnézed, akkor milyen időket ad vissza? Vannak eltérések?

**Comment by passatgt** [comment]
Köszi, megnézem majd. Viszont most kicsit indokolatlanná vált a fejlesztés, mert pont WooCommerce-hez csináltam volna a bővítményt:)

**Comment by danfekete** [comment]
Megvan a gond, most már tudsz beállítani leeway paramétert, mivel az nbf túl bekorlátozta a futtatást.

**Comment by passatgt** [comment]
Igen, tegnap láttam a leeway-es módosítást, így már működött tökéletesen, köszi.

**Comment by kratam** [comment]
Sziasztok,

elnézést hogy ide írom be, a [node-billingot](https://github.com/ghostmonitor/node-billingo) használom, és ugyanezt a hibát kapom a szerveren pár napja (`Cannot handle token prior to XXX`). Local-ban működik.
Ez ott a token generálás, van ötletetek, mit kéne máshogy?
```
  token () {
    const ts = moment().unix()
    return jwt.encode({
      sub: this._options.key,
      iat: ts,
      exp: moment().add(60, 'seconds').unix(),
      iss: 'cli',
      jti: md5(this._options.key + ts)
    }, this._options.secret)
  }
```

Előre is köszönöm.

**Comment by danfekete** [comment]
@csiszi: `iat` paraméter legyen `ts-60` másodperc, `nbf` -et nem használsz? Ha mégis akkor az is legyen `ts-60` másodperc

**Comment by kratam** [comment]
Köszi, működött az iat-60s. Ez nem az én kódom, a node-billingo package-et használom, abból másoltam ki.
