### ISSUE TITLE
Kevesen használják ezt a csomagot

### ISSUE THREAD

**Issue by szepeviktor** [voov/Billingo-API-Connector#32]
Katt: https://packagist.org/packages/voov/billingo-api-connector/stats

Valami baj lehet.

- nehéz használni
- nincs kikommunikálva
- ilyen a magyar piac??

**Comment by szepeviktor** [comment]
Ha majd elkezdem használni a Billingot, akkor lesz egy szkriptem, ami egy csinos whiptail (terminálos) menüben kiválasztatja a Vevő nevét, és már nyomatja is a számlát!

- kiállítás
- PDF elküldés email-ben
- PDF lementés egy erre dedikált S3 bucket-be 🚀

**Comment by danfekete** [comment]
Szia,
- Az API doksiban kommunikáljuk mivel ott van a legtöbb értelme
- Csak azért létezik, hogy néhány usernek megkönnyítse az implementációt, de mivel teljesen REST alapú az API ezért sokan inkább az saját függvényeiket használják
