### ISSUE TITLE
Él még ez a projekt?

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [voov/Billingo-API-Connector#39]
Nem látok válaszokat az issue-kra és pull request-ek is be vannak ragadva. A projektet tekintsük abandoned-nek, vagy esetleg várható valamilyen nagyobb update, pl a 3-as billingo api-ra való átállás?

**Comment by akosphp** [comment]
Eléggé úgy tűnik, hogy abandoned. Mostanra már biztonsági probléma is van a függőségekben található régi firebase/php-jwt csomag miatt.

**Comment by meszaros-lajos-gyorgy** [comment]
@akosphp akkor én szerintem a te fork-odat fogom használni, aztán ha van valami új fícsör ötlet, akkor inkább oda csinálok pull request-et.
Másnak is ajánlom ezt a jelenlegi repo helyett: https://packagist.org/packages/akosphp/billingo-api-connector
